config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  root to: 'warehouses#index'

  # Warehouses with nested Items
  resources :warehouses do
    resources :items, only: %i[show]
  end

  # Items
  resources :items, only: %i[new create edit update delete]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
# app/models/item.rb
class Item < ApplicationRecord
  belongs_to :warehouse
  validates :name, :type_of_item, presence: true
  enum type_of_item: { beehives: 0, books: 1, clothes: 2, computers: 3, paintings: 4, billard_balls: 5 }
end

app/models/warehouse.rb
# app/models/warehouse.rb
class Warehouse < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, :address, :capacity, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
# app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :item_check, only: %i[show edit update destroy]

  def show; end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @warehouse = Warehouse.find(params[:item][:warehouse_id])
    @item.warehouse = @warehouse
    if @item.save!
      redirect_to warehouse_path(@warehouse)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @item.update(item_params)
      redirect_to warehouse_path(@item.warehouse), notice: 'Your amazing Item is edited!'
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path,
                status: :see_other,
                data: { turbo_confirm: 'Are you sure you want to delete this beautiful Item?' }
  end

  private

  def item_check
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :type_of_item, :warehouse_id)
  end
end

app/controllers/warehouses_controller.rb
# app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :warehouse_check, only: %i[show edit update destroy]

  def index
    @warehouses = Warehouse.all.reverse
  end

  def show; end

  def new
    @warehouse = Warehouse.new
  end

  def create
    @warehouse = Warehouse.new(warehouse_params)
    if @warehouse.save
      redirect_to @warehouse
    else
      render :new
    end
  end

  def edit; end

  def update
    if @warehouse.update(warehouse_params)
      redirect_to @warehouse, notice: 'Your amazing warehouse is edited!'
    else
      render :edit
    end
  end

  def destroy
    @warehouse.destroy
    redirect_to warehouses_path,
                status: :see_other,
                data: { turbo_confirm: 'Are you sure you want to delete this beautiful Warehouse?' }
  end

  private

  def warehouse_check
    @warehouse = Warehouse.find(params[:id])
  end

  def warehouse_params
    params.require(:warehouse).permit(:name, :address, :capacity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/views/items/edit.html.erb
<%# app/views/items/edit.html.erb %>
<h1>Edit your beautiful Item! 🐝 🎱 📚 🖼</h1>

<%= form_for(@item) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :type_of_item %>
<%= f.select :type_of_item, ['beehives', 'books', 'clothes', 'computers', 'paintings', 'billard_balls'] %>
<%= f.submit "Edit Item"%>
<% end %>

app/views/items/new.html.erb
<%# app/views/items/new.html.erb %>
<h1>Tell us about your new Item! 🐝 🎱 📚 🖼</h1>
<%= form_for @item, url: items_path do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :warehouse %>
<%= f.collection_select :warehouse_id, Warehouse.all, :id, :name %>
<%= f.label :type_of_item %>
<%= f.select :type_of_item, ['beehives', 'books', 'clothes', 'computers', 'paintings', 'billard_balls'] %>
<%= f.submit "New Item" %>
<% end %>

app/views/items/show.html.erb
<%# app/views/items/show.html.erb %>
<div class="container">
  <h1>Welcome to a specific Inventrack Item Show Page! 🐝 🎱 📚 🖼</h1>
      <div class="info">
          <h1><%= @item.name %></h1>
          <h2>This item has the type of:</h4>
          <h3><%= @item.type_of_item %></h3>
          <h2>The item is located in this Warehouse:</h4>
          <h3><%= @item.warehouse.name %></h3>
          <%= link_to "Update", edit_item_path(@item) %>
          <%= link_to "Delete", item_path(@item), method: :delete, data: { turbo_method: :delete, confirm: "Do you really want to say bye bye to your beautiful Item?" } %>
          <%= link_to "Back to the Warehouse", warehouse_path(@item.warehouse) %>
      </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventrack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/warehouses/edit.html.erb
<%# app/views/warehouses/edit.html.erb %>
<h1>Edit your beautiful Warehouse! 🏠</h1>

<%= form_for(@warehouse) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :address %>
<%= f.text_field :address %>
<%= f.label :capacity %>
<%= f.number_field :capacity %>
<%= f.submit "Edit Warehouse"%>
<% end %>

app/views/warehouses/index.html.erb
<%# app/views/warehouses/index.html.erb %>
<h1>Welcome to the Inventrack Index Page!</h1>

<h2>🏠 Here are our Amazing Warehouses 🏠</h2>

<div class="flex-container">
  <div class="grid">
  <%= link_to "New Warehouse", new_warehouse_path %>
  <%= link_to "Add new item 🎱 🐝 👕 🖼", new_item_path %>
    <% @warehouses.each do |warehouse| %>
      <%= link_to warehouse_path(warehouse) do %>
        <div class="card">
          <div class="info">
            <h2 class="title"><%= warehouse.name %></h2>
            <p class="address"><%= warehouse.address %></p>
            <p class="capacity"><%= warehouse.capacity %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/warehouses/new.html.erb
<%# app/views/warehouses/new.html.erb %>
<h1>Tell us about your new Warehouse! 🏠</h1>
<%= form_for(@warehouse) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :address %>
<%= f.text_field :address %>
<%= f.label :capacity %>
<%= f.number_field :capacity %>
<%= f.submit %>
<% end %>

app/views/warehouses/show.html.erb
<%# app/views/warehouses/show.html.erb %>
<div class="container">
  <h1>Welcome to a specific Inventrack Warehouse Show Page! 🏠</h1>
      <div class="info">
          <h1><%= @warehouse.name %></h1>
          <h2>This warehouse is located in:</h4>
          <h3><%= @warehouse.address %></h3>
          <h2>The capacity of this warehouse is:</h4>
          <h3><%= @warehouse.capacity %></h3>
          <ul>
            <% @warehouse.items.each do |item| %>
            <li>
              <%= link_to item.name, [@warehouse, item] %>
            </li>
            <% end %>
          </ul>
          <%= link_to "Update", edit_warehouse_path(@warehouse) %>
          <%= link_to "Delete", warehouse_path(@warehouse), method: :delete, data: { turbo_method: :delete, confirm: "Do you really want to say bye bye to your beautiful Warehouse?" } %>
          <%= link_to "Back to all Warehouses", warehouses_path %>
      </div>
</div>